# Alumno: Pablo Matías Monsalvo G8-ONE
### Pandas E/S: Trabajando con direntes formatos de archivos
## **Aula 1 - Leyendo archivos CSV**

###**Importando archivos CSV**

In [1]:
import pandas as pd

In [2]:
datos = pd.read_csv('../data/superstore_data.csv')

In [3]:
datos.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [4]:
datos_punto_coma = pd.read_csv('../data/superstore_data_punto_coma.csv')

In [5]:
datos_punto_coma.head()

Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...                                                                                                                                                                                                                             
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...                                                                                                                                                                                                                             
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...                                                                                                                                                                                                                             
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...                                                                                                                                                                                                                             
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

##  04 Para saber más: error de codificación - ¿cómo solucionarlo?

Giovanna es una científica de datos que trabaja en una empresa de comercio electrónico. Ella es responsable de analizar datos de ventas para identificar patrones y tendencias que puedan ayudar a la empresa a tomar decisiones informadas.

Recientemente, le asignaron una nueva tarea: analizar un archivo CSV que contiene información sobre las ventas de la empresa durante un período determinado. Para ello, Giovanna intentó leer un archivo CSV en Google Colab, usando la biblioteca Pandas con el siguiente comando:

# import pandas as pd
# df = pd.read_csv('datos.csv')

Sin embargo, apareció el siguiente error:

En español, el mensaje significa UnicodeDecodeError: el códec 'utf-8' no puede decodificar el byte 0xff en la posición 0: byte de inicio inválido

Pero ¿qué significa eso? ¿Qué es esto de UTF-8?

El error de encoding ocurre cuando la biblioteca Pandas no puede interpretar correctamente los caracteres en un archivo CSV. Esto puede suceder cuando contiene caracteres especiales que la biblioteca Pandas no reconoce o cuando se guardó en un formato de codificación diferente al esperado.

Para resolver este error, es necesario identificar la codificación correcta del archivo CSV y especificarla al cargar el archivo con la biblioteca Pandas. Esta codificación predeterminada es UTF-8, pero en algunos casos, es posible que el archivo se haya guardado con una codificación diferente, como ISO-8859-1.

UTF-8 es una codificación de caracteres universal que se utiliza para representar caracteres de diferentes idiomas de una manera compatible con Internet y los sistemas de computadora en general. Las siglas UTF significan Unicode Transformation Format (Formato de Transformación Unicode) y el número 8 indica que esta codificación asocia una secuencia de 1 a 4 bytes (8 a 32 bits) a cada carácter.

La codificación UTF-8 se usa ampliamente en Internet y en sistemas informáticos de todo el mundo, ya que permite representar caracteres de diferentes idiomas en un solo conjunto de caracteres. Además, esta codificación puede preservar la compatibilidad con codificaciones más antiguas como ASCII, lo que la convierte en una opción popular para crear y compartir archivos de texto.

Quizás estés pensando ahora mismo: ¿cómo podría Giovanna descubrir cuál es la codificación del archivo que está intentando leer?

Hay algunas formas de resolver esto, sin embargo, tendremos la oportunidad de experimentar una forma práctica de hacerlo en el propio Google Colab. ¿Vamos allá?

Podemos usar una biblioteca llamada chardet para detectar el encoding de un archivo CSV. Para usar esta biblioteca en Google Colab, simplemente importela:

# import chardet

Luego escribimos el siguiente bloque de código:

# with open('datos.csv', 'rb') as file:
  #  print(chardet.detect(file.read()))

Observe que la primera línea de este código abre el archivo CSV en modo de lectura binaria rb y asigna el objeto del archivo devuelto a una variable llamada file.

En la segunda línea de código, el contenido del archivo CSV se lee usando el método read() y el resultado se pasa a la función chardet.detect(), que devuelve un diccionario que contiene información sobre la codificación más probable del archivo. El resultado se imprime con la función print() que muestra la codificación y la confianza asociada con esa codificación.

Al ejecutar el código Giovanna obtuvo el siguiente resultado:

# {'encoding': 'UTF-16', 'confidence': 1.0, 'language': ''}

Ahora ella sabe que es probable que el archivo CSV esté codificado con UTF-16 con una confianza de 1.0. Para especificar la codificación correcta al cargar el archivo CSV con la biblioteca Pandas, puede utilizar un parámetro llamado encoding:

# df = pd.read_csv('datos.csv', encoding='UTF-16')

De esta manera, la biblioteca Pandas cargará el archivo CSV usando la codificación UTF-16, lo que resolverá el error de codificación. Entonces, si alguna vez intentas leer un archivo y obtienes el mismo error, ¡recuerda este consejo!

Si deseas profundizar más en el tema, aquí te dejamos algunos enlaces a materiales que fueron utilizados como referencia:

Instituto de Matemáticas y Estadística - IME/USP: Unicode y UTF-8
IBM: ¿Qué es Unicode?
Kaggle: codificaciones de caracteres

In [8]:
pip install chardet

  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Note: you may need to restart the kernel to use updated packages.


In [9]:
import chardet

In [10]:
with open('../data/superstore_data.csv','rb')as file:
    print(chardet.detect(file.read()))

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}


###**Parámetros de la función read_csv**
Documentación: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

In [6]:
datos_punto_coma = pd.read_csv('../data/superstore_data_punto_coma.csv', sep = ';')

In [11]:
datos_punto_coma.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [12]:
datos_primeras_lineas = pd.read_csv('../data/superstore_data.csv',nrows=5)
datos_primeras_lineas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [13]:
datos_seleccion = pd.read_csv('../data/superstore_data.csv', usecols=['Id', 'Year_Birth', 'Income'])
datos_seleccion

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [15]:
datos_seleccion = pd.read_csv('../data/superstore_data.csv', usecols=[0,1,4])
datos_seleccion

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

## 06 Leyendo un archivo CSV

Juliana está trabajando en un proyecto de análisis de datos de ventas para una tienda minorista. Ella recibió un conjunto de datos en formato CSV con los valores separados por punto y coma y necesita importarlo a un DataFrame de la biblioteca Pandas para iniciar el análisis.

¿Cuál es la forma correcta de leer este archivo CSV usando la biblioteca Pandas?

# pd.read_csv(‘datos_ventas.csv’, sep=‘;’)

Al leer un archivo CSV con la biblioteca Pandas, es importante especificar el separador de campo correcto usando el parámetro sep. La opción predeterminada es una coma (','), por lo que debemos agregar el separador ;



### **Escribiendo archivos CSV**

Documentación: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

In [17]:
datos_seleccion.to_csv('clientes_mercado.csv')

In [18]:
clientes_mercado = pd.read_csv('../data/clientes_mercado.csv')
clientes_mercado

Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

In [19]:
datos_seleccion.to_csv('datos_mercado.csv', index=False)

In [21]:
datos_mercado = pd.read_csv('../data/datos_mercado.csv')
datos_mercado

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

##  08 - Para saber más: explorando la documentación

La biblioteca Pandas es una de las herramientas más poderosas disponibles para análisis de datos en Python. Ofrece una amplia variedad de funciones que hacen que el proceso de manipulación y análisis de datos sea mucho más fácil y eficiente.

Para aprovechar al máximo todas las funciones de la biblioteca, es esencial explorar su documentación, que es extensa y está bien organizada, y a la que se puede acceder fácilmente en línea. Consulta las indicaciones:

Función read_csv
Función to_csv
Explorar la documentación de la biblioteca es importante por varias razones. Puede ayudarle a comprender cómo las funciones y métodos de la biblioteca funcionan y cómo se pueden utilizar para analizar y manipular datos.

Además, la documentación proporciona detalles sobre los parámetros de cada función y ejemplos de cómo se pueden utilizar en la práctica. Entonces, intenta profundizar tus estudios sobre los parámetros de cada función read_csv y to_csv y aprende más sobre cada uno de ellos.

##  09 Desafío: leyendo datos con múltiples parámetros

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Disponemos de un archivo en formato CSV, el cual se obtuvo de la página Información de Salud (TABNET) - DATASUS. Este archivo contiene los gastos hospitalarios públicos de cada una de las Unidades de la Federación Brasileña desde enero de 2008 hasta marzo de 2021.

Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:

* 1-Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.
* 2-La codificación del archivo es ISO-8859-1.
* 3-Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.
* 4-Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.
* 5-Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.
¿Comenzamos?

Procedimentos hospitalares do SUS - por local de interna��o - Brasil
Valor total por Unidade da Federa��o e Ano/m�s processamento
Per�odo:Jan/2008-Mar/2021
"Unidade da Federa��o";"2008/Jan";"2008/Fev";"2008/Mar";"2008/Abr";"2008/Mai";"2008/Jun";"2008/Jul";"2008/Ago";"2008/Set";"2008/Out";"2008/Nov";"2008/Dez";"2009/Jan";"2009/Fev";"2009/Mar";"2009/Abr";"2009/Mai";"2009/Jun";"2009/Jul";"2009/Ago";"2009/Set";"2009/Out";"2009/Nov";"2009/Dez";"2010/Jan";"2010/Fev";"2010/Mar";"2010/Abr";"2010/Mai";"2010/Jun";"2010/Jul";"2010/Ago";"2010/Set";"2010/Out";"2010/Nov";"2010/Dez";"2011/Jan";"2011/Fev";"2011/Mar";"2011/Abr";"2011/Mai";"2011/Jun";"2011/Jul";"2011/Ago";"2011/Set";"2011/Out";"2011/Nov";"2011/Dez";"2012/Jan";"2012/Fev";"2012/Mar";"2012/Abr";"2012/Mai";"2012/Jun";"2012/Jul";"2012/Ago";"2012/Set";"2012/Out";"2012/Nov";"2012/Dez";"2013/Jan";"2013/Fev";"2013/Mar";"2013/Abr";"2013/Mai";"2013/Jun";"2013/Jul";"2013/Ago";"2013/Set";"2013/Out";"2013/Nov";"2013/Dez";"2014/Jan";"2014/Fev";"2014/Mar";"2014/Abr";"2014/Mai";"2014/Jun";"2014/Jul";"2014/Ago";"2014/Set";"2014/Out";"2014/Nov";"2014/Dez";"2015/Jan";"2015/Fev";"2015/Mar";"2015/Abr";"2015/Mai";"2015/Jun";"2015/Jul";"2015/Ago";"2015/Set";"2015/Out";"2015/Nov";"2015/Dez";"2016/Jan";"2016/Fev";"2016/Mar";"2016/Abr";"2016/Mai";"2016/Jun";"2016/Jul";"2016/Ago";"2016/Set";"2016/Out";"2016/Nov";"2016/Dez";"2017/Jan";"2017/Fev";"2017/Mar";"2017/Abr";"2017/Mai";"2017/Jun";"2017/Jul";"2017/Ago";"2017/Set";"2017/Out";"2017/Nov";"2017/Dez";"2018/Jan";"2018/Fev";"2018/Mar";"2018/Abr";"2018/Mai";"2018/Jun";"2018/Jul";"2018/Ago";"2018/Set";"2018/Out";"2018/Nov";"2018/Dez";"2019/Jan";"2019/Fev";"2019/Mar";"2019/Abr";"2019/Mai";"2019/Jun";"2019/Jul";"2019/Ago";"2019/Set";"2019/Out";"2019/Nov";"2019/Dez";"2020/Jan";"2020/Fev";"2020/Mar";"2020/Abr";"2020/Mai";"2020/Jun";"2020/Jul";"2020/Ago";"2020/Set";"2020/Out";"2020/Nov";"2020/Dez";"2021/Jan";"2021/Fev";"2021/Mar";"Total"
"Rond�nia";1388528,39;2931283,42;1541682,52;1525314,96;1645953,84;1406150,68;3065279,01;3231494,61;3117178,63;3068430,44;2825838,52;2931173,58;2885269,07;2860103,74;3684944,68;3607289,68;3774356,60;3706711,84;3763187,55;3533625,83;3605007,43;3907032,72;3939820,71;3901084,11;3684407,02;3623015,58;3890461,90;4193533,87;4534400,67;4451208,03;4874592,78;4460802,38;5067886,24;4511092,85;4394680,50;4098741,80;4411499,48;3868617,95;4298702,78;5062171,26;4769347,86;4578105,60;4477870,09;5173453,51;5554791,51;4110177,87;4428561,32;
"R

## Opinión del instructor

Para leer el archivo podemos comenzar almacenando la dirección en una variable llamada url:

In [8]:
import pandas as pd

# Define la ruta relativa al archivo
# Esta ruta asume que el script/notebook se está ejecutando desde
# el directorio 'ipynb-alura' (un nivel arriba de 'data').
url = '../data/datos_sus.csv'

# Lee el archivo CSV con los parámetros especificados
datos_sus = pd.read_csv(url,
                        encoding='ISO-8859-1',
                        sep=';',
                        skiprows=3,  # ¡Corregido aquí!
                        skipfooter=9,
                        engine='python')

# Muestra las primeras filas para verificar que la lectura fue correcta
datos_sus.head()

Unidade da Federação     2008/Jan     2008/Fev     2008/Mar     2008/Abr  \
0             Rondônia   1388528,39   2931283,42   1541682,52   1525314,96   
1                 Acre    902416,00   1497206,26   1794028,48   1730469,42   
2             Amazonas   4735529,42   7118990,57   8196635,49   8259378,42   
3              Roraima    657889,53    777939,31    718688,03    839994,39   
4                 Pará  18864744,11  19553758,20  21937342,70  20842829,69   

      2008/Mai     2008/Jun     2008/Jul     2008/Ago     2008/Set  ...  \
0   1645953,84   1406150,68   3065279,01   3231494,61   3117178,63  ...   
1   1819443,92   1828496,00   2511754,59   2089107,14   2275708,53  ...   
2   7831399,90   8477273,62   9368858,72   9352532,70   9363099,35  ...   
3    862347,96    832440,66    996693,09    894271,18    910424,17  ...   
4  23249952,88  23240687,56  24002223,56  23341218,03  25172261,32  ...   

      2020/Jul     2020/Ago     2020/Set     2020/Out     2020/Nov  \
0  11824687,13  11733307,76  10201985,14   7955139,45   9357946,29   
1   3915193,20   3640142,82   3391242,21   4044321,44   3276590,10   
2  19769460,14  18059931,43  17841015,63  16408315,10  19895617,91   
3   3015488,30   2826486,18   2928043,91   3090313,73   3621031,05   
4  40804126,43  44385715,88  36820249,47  36965931,34  39004315,80   

      2020/Dez     2021/Jan     2021/Fev     2021/Mar          Total  
0   8880836,55   9266014,59   7730597,04  11023309,47   996411254,68  
1   3696997,31   3715723,12   3538427,92   4077045,92   450048530,47  
2  17765167,69  21430289,17  25917134,55  22032176,22  1917247936,05  
3   3454460,94   3266928,47   3519773,73   3985530,08   328876965,09  
4  38015145,79  38354682,46  37688314,23  33276392,89  4705309002,29  

[5 rows x 161 columns]

Luego podemos leer la url con la función read_csv y agregar los parámetros:

* encoding='ISO-8859-1': tipo de codificación de caracteres del archivo. En este caso, es la codificación ISO-8859-1 la que es común en los archivos en idioma portugués.
* sep=';': separador de los valores del archivo. En este caso, es el punto y coma (;).
* skiprows=3: indica que las primeras tres líneas del archivo deben ignorarse ya que no contienen datos relevantes.
* skipfooter=9: Indica que las últimas nueve líneas del archivo deben ignorarse ya que no contienen datos relevantes.
* engine='python': el motor utilizado para leer el archivo es Python. Esto es necesario cuando se utiliza el parámetro skipfooter, ya que el motor predeterminado no admite esta opción.

# 10 Lo que aprendimos


### En esta aula, aprendimos:

* Entender qué es un archivo CSV;
* Leer un archivo en formato CSV separado por comas y punto y coma;
* Leer sólo unas pocas líneas y también columnas específicas de un archivo en formato CSV;
* Escribir un archivo en formato CSV.

## **Aula 2 - Leyendo archivos Excel**

### **Importando archivos Excel**

In [10]:
pip install  openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [4]:
archivo = '../data/emisiones_CO2.xlsx'

In [12]:
datos_co2 = pd.read_excel(archivo)

In [13]:
datos_co2.head()

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  Cemento  \
0  Afganistán                AFG  1750    0.0     NaN     NaN  NaN      NaN   
1  Afganistán                AFG  1751    0.0     NaN     NaN  NaN      NaN   
2  Afganistán                AFG  1752    0.0     NaN     NaN  NaN      NaN   
3  Afganistán                AFG  1753    0.0     NaN     NaN  NaN      NaN   
4  Afganistán                AFG  1754    0.0     NaN     NaN  NaN      NaN   

   Quema  Otros  Per Capita  
0    NaN    NaN         NaN  
1    NaN    NaN         NaN  
2    NaN    NaN         NaN  
3    NaN    NaN         NaN  
4    NaN    NaN         NaN

In [14]:
datos_co2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63104 entries, 0 to 63103
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   País                63104 non-null  object 
 1   ISO 3166-1 alpha-3  61472 non-null  object 
 2   Año                 63104 non-null  int64  
 3   Total               62904 non-null  float64
 4   Carbón              21744 non-null  float64
 5   Aceite              21717 non-null  float64
 6   Gas                 21618 non-null  float64
 7   Cemento             20814 non-null  float64
 8   Quema               21550 non-null  float64
 9   Otros               1620 non-null   float64
 10  Per Capita          18974 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 5.3+ MB


In [15]:
pd.ExcelFile(archivo).sheet_names

['emisiones_C02', 'emisiones_percapita', 'fuentes']

## 03 Para saber más: profundizando en la función read_excel

Microsoft Excel es una de las herramientas de hojas de cálculo más utilizadas en el mundo, siendo ampliamente utilizada para almacenar y analizar datos en formato de tabla. En el video anterior, mostramos cómo la función read_excel se puede usar para leer un archivo de Excel en formato xlsx. Sin embargo, esta función es capaz de leer archivos en otros formatos, como: xls, xlsm, xlsb, odf, ods y odt.

¿Vamos a entender un poco más sobre estos diferentes tipos de archivos?

# xls

El formato xls es un formato de archivo de Excel más antiguo y se utilizó hasta la versión de 2003.

# xlsx

El formato xlsx es el formato de archivo de Excel predeterminado a partir de la versión 2007. Este formato se basa en XML(Extensible Markup Language - Lenguaje de marcación extensible) y es ampliamente compatible con otras herramientas de hojas de cálculo online, incluida Google Sheets.

Atención : Si tienes dudas sobre el término XML, ¡no te preocupes! Tendremos un aula sobre este tema más adelante. En ella entenderás qué es este formato, cómo leer y escribir en XML.

# xlsm

También existe xlsm, una extensión de archivo utilizada por Excel para almacenar hojas de cálculo que contienen macros. Son secuencias de comandos o instrucciones que se pueden ejecutar automáticamente para realizar tareas específicas en la hoja de trabajo.

Entonces, el formato xlsm permite guardar las macros junto con la hoja de trabajo, de modo que puedan ejecutarse cada vez que se abra la hoja de trabajo.

# xlsb

Por último, tenemos el formato xlsb, una extensión de archivo que utiliza Excel para almacenar hojas de cálculo en formato binario. La codificación binaria permite abrir y guardar hojas de cálculo más rápido que aquellas en formato xlsx.

Los formatos odf, ods y odt son archivos abiertos, gratuitos y universales que pueden ser utilizados por cualquier software, es decir, fueron creados para ser independientes de plataformas, esto quiere decir que pueden ser utilizados en diferentes sistemas operativos, como Windows, Linux y Mac OS.

Además, son independientes de aplicaciones y se pueden utilizar en muchos programas diferentes, incluidos OpenOffice, LibreOffice, Google Docs y Microsoft Office. Este estándar de archivos fue creado y es mantenido por OASIS (Organization for the Advancement of Structured Information Standards), una organización internacional creada para desarrollar y promover estándares digitales para su uso en Internet.

¡Muy bien! Ahora sabemos un poco más sobre todos los tipos de archivos que se pueden leer con la función read_excel.

Si deseas profundizar más en el tema, aquí te dejamos algunos enlaces a materiales que fueron utilizados como referencia:

* Formatos de archivo compatibles con Excel
* OpenDocument

### **Parámetros de la función read_excel**

Documentación: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

In [16]:
percapita = pd.read_excel(archivo, sheet_name='emisiones_percapita')

In [17]:
percapita.head()

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  Cemento  \
0  Afganistán                AFG  1750    NaN     NaN     NaN  NaN      NaN   
1  Afganistán                AFG  1751    NaN     NaN     NaN  NaN      NaN   
2  Afganistán                AFG  1752    NaN     NaN     NaN  NaN      NaN   
3  Afganistán                AFG  1753    NaN     NaN     NaN  NaN      NaN   
4  Afganistán                AFG  1754    NaN     NaN     NaN  NaN      NaN   

   Quema  Otros  
0    NaN    NaN  
1    NaN    NaN  
2    NaN    NaN  
3    NaN    NaN  
4    NaN    NaN

In [18]:
percapita.tail()

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
63099  Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100  Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101  Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102  Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103  Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gas   Cemento    Quema    Otros  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0

In [21]:
percapita.sample(5)

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  \
1386     Anguila                AIA  1776    NaN     NaN     NaN  NaN   
29105     Kuwait                KWT  1751    NaN     NaN     NaN  NaN   
16213     Egipto                EGY  1915    NaN     NaN     NaN  NaN   
33578     Malaui                MWI  1872    NaN     NaN     NaN  NaN   
55829  Tailandia                THA  1819    NaN     NaN     NaN  NaN   

       Cemento  Quema  Otros  
1386       NaN    NaN    NaN  
29105      NaN    NaN    NaN  
16213      NaN    NaN    NaN  
33578      NaN    NaN    NaN  
55829      NaN    NaN    NaN

In [22]:
fuentes = pd.read_excel(archivo, sheet_name='fuentes')

In [12]:
fuentes.head()

País ISO 3166-1 alpha-3   Año   Total  Carbón  Aceite     Gas  \
0  Afganistán                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afganistán                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afganistán                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afganistán                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afganistán                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cemento   Quema   Otros Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

In [23]:
fuentes.sample(5)

País ISO 3166-1 alpha-3   Año       Total  \
47884             Santa Elena                SHN  1762      [NONE]   
59041  Emiratos Árabes Unidos                ARE  1767      [NONE]   
44200                 Polonia                POL  1886  CDIAC 2022   
61329                 Vietnam                VNM  1879      [NONE]   
41920                Pakistán                PAK  1782      [NONE]   

           Carbón      Aceite         Gas Cemento       Quema   Otros  \
47884      [NONE]      [NONE]      [NONE]  [NONE]      [NONE]  [NONE]   
59041      [NONE]      [NONE]      [NONE]  [NONE]      [NONE]  [NONE]   
44200  CDIAC 2022  CDIAC 2022  CDIAC 2022  [NONE]  CDIAC 2022  [NONE]   
61329      [NONE]      [NONE]      [NONE]  [NONE]      [NONE]  [NONE]   
41920      [NONE]      [NONE]      [NONE]  [NONE]      [NONE]  [NONE]   

       Per Capita  
47884      [NONE]  
59041      [NONE]  
44200  CDIAC 2022  
61329      [NONE]  
41920      [NONE]

In [24]:
fuentes.tail()

País ISO 3166-1 alpha-3   Año                                 Total  \
63099  Global                WLD  2017  CDIAC 2022, BP, and Sum of countries   
63100  Global                WLD  2018  CDIAC 2022, BP, and Sum of countries   
63101  Global                WLD  2019  CDIAC 2022, BP, and Sum of countries   
63102  Global                WLD  2020  CDIAC 2022, BP, and Sum of countries   
63103  Global                WLD  2021  CDIAC 2022, BP, and Sum of countries   

                  Carbón             Aceite                Gas        Cemento  \
63099  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63100  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63101  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63102  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63103  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   

                    Quema   Otros  \
63099  CDIAC 2022 and GCP  [NONE]   
63100  CDIAC 2022 and GCP  [NONE]   
63101  CDIAC 2022 and GCP  [NONE]   
63102  CDIAC 2022 and GCP  [NONE]   
63103  CDIAC 2022 and GCP  [NONE]   

                                              Per Capita  
63099  CDIAC 2022, BP, Sum of countries, and UN popul...  
63100  CDIAC 2022, BP, Sum of countries, and UN popul...  
63101  CDIAC 2022, BP, Sum of countries, and UN popul...  
63102  CDIAC 2022, BP, Sum of countries, and UN popul...  
63103  CDIAC 2022, BP, Sum of countries, and UN popul...

In [25]:
intervalo = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols= 'A:D')

In [26]:
intervalo

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [27]:
intervalo_2 = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols= 'A:D', nrows=10)

In [28]:
intervalo_2

País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

##  05 Leyendo intervalos

Théo está trabajando en una análisis de datos en Python utilizando la biblioteca Pandas. Él está utilizando una hoja de cálculo de Excel que tiene 4 páginas y quiere leer sólo una de las tablas contenidas en una de ellas. La tabla que quiere leer está en la página "pagos" y los datos están en las primeras 50 filas desde la columna F hasta la columna L de la hoja de cálculo.

¿Cuál es el código correcto que debería usar Théo para leer sólo el intervalo deseado?

### df = pd.read_excel('datos.xlsx', sheet_name=’pagos’, usecols='F:L', nrows=50)

El parámetro sheet_name se utiliza para especificar la página de la hoja de cálculo que Théo quiere leer. En este caso, es la página "pagos". El parámetro usecols se utiliza para especificar las columnas que se leerán, que son las columnas de la F a la L. Además, el parámetro nrows se agregó para especificar el número de líneas que Théo quiere leer, que es 50.

### **Escribiendo archivos Excel**

In [32]:
intervalo.to_excel('co2_percapita.xlsx', index=False)

In [35]:
pd.read_excel('../data/co2_percapita.xlsx')

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

#  07 Para saber más: importando hacia Google Sheets

Google Sheets es una herramienta de hojas de cálculo online basada en nube que le permite crear, editar y colaborar en hojas de cálculo de manera fácil y conveniente. Es una de las aplicaciones de Google Workspace que ofrece una alternativa a Microsoft Excel.

Con Google Sheets se puede crear y formatear hojas de cálculo, agregar fórmulas y funciones, crear gráficos y tablas dinámicas y trabajar con otros usuarios con datos en tiempo real. También admite la importación y exportación de varios formatos de archivos, como CSV y XLSX.

Una de las principales ventajas de Google Sheets es la colaboración en tiempo real. Varias personas pueden trabajar simultáneamente en la misma hoja de trabajo y ver los cambios simultáneamente. Esto facilita el trabajo en proyectos de equipo, aumentando la eficiencia y la productividad.

Para importar el archivo de Excel emisiones_CO2.xlsx hacia Google Sheets, siga estos pasos:

* Abra la página de Google Sheets y haga clic en "Ir a Sheets". Inicie sesión en su cuenta de Google si es necesario.
* Haga clic en Nueva Hoja de cálculo en blanco.
* Cuando haya abierto, haga clic en "Archivo" (File) en el menú superior y luego haga clic en la opción "Importar archivo" (Import).
* Haga clic en la pestaña "Subir" (Upload) y seleccione el archivo que desea importar. Puede hacer clic en la opción Examinar para ubicar el archivo en su computadora o arrastrar el archivo dentro de la pestaña.
* Espere mientras se carga el archivo. Cuando se complete la carga, verá un mensaje de confirmación y podrá hacer clic en "Importar datos" (Import data).
* Después de importar, se mostrarán los datos.

¡Excelente! Los datos se han importado correctamente. En el siguiente video, aprenderá cómo leer estos datos en Google Colab usando el link para compartir de Google Sheets.



### **Leyendo datos de Google Sheets**

link:https://docs.google.com/spreadsheets/d/1DYhViiMjMqOYBpKAUThL4PUx35k4cY91hlzFJI6BldA/edit?gid=1140520571#gid=1140520571

In [50]:
sheet_id = '1DYhViiMjMqOYBpKAUThL4PUx35k4cY91hlzFJI6BldA' # Mi id de Google Sheets emisiones_CO2.xlsx
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [51]:
datos_co2_sheets = pd.read_csv(url)
datos_co2_sheets

País ISO 3166-1 alpha-3   Año           Total          Carbón  \
0      Afganistán                AFG  1750               0             NaN   
1      Afganistán                AFG  1751               0             NaN   
2      Afganistán                AFG  1752               0             NaN   
3      Afganistán                AFG  1753               0             NaN   
4      Afganistán                AFG  1754               0             NaN   
...           ...                ...   ...             ...             ...   
63099      Global                WLD  2017  36,096,739,276  14,506,973,805   
63100      Global                WLD  2018  36,826,506,600  14,746,830,688   
63101      Global                WLD  2019  37,082,558,969  14,725,978,025   
63102      Global                WLD  2020  35,264,085,734  14,174,564,010   
63103      Global                WLD  2021  37,123,850,352  14,979,598,083   

               Aceite            Gas        Cemento        Quema        Otros  \
0                 NaN            NaN            NaN          NaN          NaN   
1                 NaN            NaN            NaN          NaN          NaN   
2                 NaN            NaN            NaN          NaN          NaN   
3                 NaN            NaN            NaN          NaN          NaN   
4                 NaN            NaN            NaN          NaN          NaN   
...               ...            ...            ...          ...          ...   
63099  12,242,627,935  7,144,928,128  1,507,923,185  391,992,176  302,294,047   
63100  12,266,016,285  7,529,846,784  1,569,218,392  412,115,746  302,478,706   
63101  12,345,653,374  7,647,528,220  1,617,506,786  439,253,991  306,638,573   
63102  11,191,808,551  7,556,290,283  1,637,537,532  407,583,673  296,301,685   
63103  11,837,159,116  7,921,829,472  1,672,592,372  416,525,563  296,145,746   

      Per Capita  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
63099  4,749,682  
63100  4,792,753  
63101  4,775,633  
63102  4,497,423  
63103  4,693,699  

[63104 rows x 11 columns]

link: https://docs.google.com/spreadsheets/d/1Iedfu3ShscnDp_XUr4ndPP3_WAdTVWaQdx_EbJuTmbE/edit?gid=481919613#gid=481919613

In [ ]:
sheet_id = '1Iedfu3ShscnDp_XUr4ndPP3_WAdTVWaQdx_EbJuTmbE' # Mi id de Google Sheets co2_percapita.xlsx
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [53]:
datos_co2_sheets = pd.read_csv(url)
datos_co2_sheets

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [ ]:
# sheet_id = '1mRsV8OYjogOx_6neuNbboxvJaRpySydVN7mn6zBOn0I' # del profe
# url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [54]:
sheet_id = '1DYhViiMjMqOYBpKAUThL4PUx35k4cY91hlzFJI6BldA'
sheet_name = 'emisiones_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [55]:
percapita_sheets = pd.read_csv(url_percapita)

In [56]:
percapita_sheets.head()

País ISO 3166-1 alpha-3   Año Total Carbón Aceite  Gas Cemento Quema  \
0  Afganistán                AFG  1750   NaN    NaN    NaN  NaN     NaN   NaN   
1  Afganistán                AFG  1751   NaN    NaN    NaN  NaN     NaN   NaN   
2  Afganistán                AFG  1752   NaN    NaN    NaN  NaN     NaN   NaN   
3  Afganistán                AFG  1753   NaN    NaN    NaN  NaN     NaN   NaN   
4  Afganistán                AFG  1754   NaN    NaN    NaN  NaN     NaN   NaN   

  Otros  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

In [57]:
sheet_id = '1DYhViiMjMqOYBpKAUThL4PUx35k4cY91hlzFJI6BldA'
sheet_name = 'fuentes'
url_fuentes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [58]:
fuentes_sheets = pd.read_csv(url_fuentes)

In [60]:
fuentes_sheets.head()

País ISO 3166-1 alpha-3   Año   Total  Carbón  Aceite     Gas  \
0  Afganistán                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afganistán                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afganistán                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afganistán                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afganistán                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cemento   Quema   Otros Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

In [62]:
fuentes_sheets.tail(7)

País ISO 3166-1 alpha-3   Año                                 Total  \
63097  Global                WLD  2015       CDIAC 2022 and Sum of countries   
63098  Global                WLD  2016       CDIAC 2022 and Sum of countries   
63099  Global                WLD  2017  CDIAC 2022, BP, and Sum of countries   
63100  Global                WLD  2018  CDIAC 2022, BP, and Sum of countries   
63101  Global                WLD  2019  CDIAC 2022, BP, and Sum of countries   
63102  Global                WLD  2020  CDIAC 2022, BP, and Sum of countries   
63103  Global                WLD  2021  CDIAC 2022, BP, and Sum of countries   

                  Carbón             Aceite                Gas        Cemento  \
63097         CDIAC 2022         CDIAC 2022         CDIAC 2022  Andrew cement   
63098         CDIAC 2022         CDIAC 2022         CDIAC 2022  Andrew cement   
63099  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63100  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63101  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63102  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63103  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   

                    Quema   Otros  \
63097          CDIAC 2022  [NONE]   
63098          CDIAC 2022  [NONE]   
63099  CDIAC 2022 and GCP  [NONE]   
63100  CDIAC 2022 and GCP  [NONE]   
63101  CDIAC 2022 and GCP  [NONE]   
63102  CDIAC 2022 and GCP  [NONE]   
63103  CDIAC 2022 and GCP  [NONE]   

                                              Per Capita  
63097    CDIAC 2022, Sum of countries, and UN population  
63098    CDIAC 2022, Sum of countries, and UN population  
63099  CDIAC 2022, BP, Sum of countries, and UN popul...  
63100  CDIAC 2022, BP, Sum of countries, and UN popul...  
63101  CDIAC 2022, BP, Sum of countries, and UN popul...  
63102  CDIAC 2022, BP, Sum of countries, and UN popul...  
63103  CDIAC 2022, BP, Sum of countries, and UN popul...

##  09 Desafío: leyendo datos de otro link

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Tenemos un link de Google Sheets que contiene datos importantes sobre las emisiones de dióxido de carbono en todo el mundo. El conjunto de datos se obtuvo de Kaggle y consta de las emisiones de CO2 per cápita de todos los países del mundo entre 1990 y 2019.

En este desafío, tu función es leer este link de Google Sheets y luego guardar el DataFrame obtenido en formato CSV. ¿Listo para comenzar?

# Opinión del instructor

Iniciemos creando una variable que recibirá el ID de la hoja de trabajo.

### ¿Y dónde encontramos ese id? En el propio link. Es todo lo que aparece entre d/ y /edit.

### sheet_id = '1DYhViiMjMqOYBpKAUThL4PUx35k4cY91hlzFJI6BldA'

A continuación, creamos una variable que almacenará la dirección URL, pero podemos facilitar la escritura usando una f string para el sheet_id. Después de sheet_id tenemos algunos parámetros que se deben agregar.

En este primer momento es importante acceder a la API de visualización de datos de Google. Esto permitirá mostrar los datos de la hoja de cálculo de Google Sheets en Google Colab. Entonces, el parámetro gviz/tq indica que desea acceder a la función de consulta de datos de la API de visualización de datos.

La API también proporciona una forma de recuperar datos de hojas de cálculo como CSV, que es uno de los formatos que puede leer la biblioteca Pandas. Por este motivo indicamos el uso del parámetro tqx=out:csv para que los datos se devuelvan en formato CSV. El parámetro sheet recupera todos los datos de la hoja de trabajo, incluidos los encabezados de las columnas y las filas de datos.

### url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

Una vez hecho esto, podemos leer los datos pasando la variable url a la función read_csv:

### datos = pd.read_csv(url)

Para guardar los datos en formato CSV, basta con utilizar la función to_csv y, entre paréntesis, darle un nombre al archivo agregando el parámetro index=False para que no se agregue una nueva columna de índice:

### datos.to_csv('datos_emisiones_co2.csv', index=False)

¡Listo! Pudimos leer datos de Google Sheets con la biblioteca Pandas e incluso guardamos el DataFrame que ahora se puede compartir con otras personas o ser utilizado en análisis posteriores.

# 10 Lo que aprendimos


En esta aula, aprendimos a:

* Entender lo qué es una hoja de cálculo;
* Leer un archivo en formato XLSX;
* Identificar páginas en una hoja de trabajo;
* Leer páginas e intervalos específicos de una hoja de trabajo;
* Leer sólo unas pocas líneas de una hoja de cálculo;
* Escribir un archivo en formato XLSX;
* Importar datos de Google Sheets.


## **Aula 3 - Leyendo archivos JSON**

# **Importando archivos JSON**

### *Para visualizar online: Online JSON Viewer*
![Vista del diagrama generado en JSON Viewer](assets/json-viewer.png)

In [7]:
import pandas as pd

In [8]:
datos_pacientes = pd.read_json('../data/pacientes.json')

In [9]:
datos_pacientes

ID_paciente Enfermedad_corazon    IMC Fumador Consumo_alcohol AVC  \
0              0                 No  16.60      Sí              No  No   
1              1                 No  20.34      No              No  Sí   
2              2                 No  26.58      Sí              No  No   
3              3                 No  24.21      No              No  No   
4              4                 No  23.71      No              No  No   
..           ...                ...    ...     ...             ...  ..   
995          995                 No  28.29      Sí              No  No   
996          996                 No  25.69      Sí              No  No   
997          997                 Sí  26.99      No              No  No   
998          998                 No  44.29      No              No  No   
999          999                 No  25.83      No              No  No   

     Salud_fisica  Salud_mental Dificultad_caminar Sexo_biologico Rango_edad  \
0               3            30                 No       Femenino      55-59   
1               0             0                 No       Femenino     80 ó +   
2              20            30                 No      Masculino      65-69   
3               0             0                 No       Femenino      75-79   
4              28             0                 Sí       Femenino      40-44   
..            ...           ...                ...            ...        ...   
995            10            20                 No       Femenino      65-69   
996             0             0                 No       Femenino      75-79   
997             1             0                 No      Masculino      70-74   
998            30             0                 Sí       Femenino      70-74   
999             0             0                 No      Masculino      70-74   

       Raza Diabetes Actividad_fisica Salud_general  Horas_sueño Asma  \
0    Blanca       Sí               Sí     Muy buena            5   Sí   
1    Blanca       No               Sí     Muy buena            7   No   
2    Blanca       Sí               Sí     Razonable            8   Sí   
3    Blanca       No               No         Buena            6   No   
4    Blanca       No               Sí     Muy buena            8   No   
..      ...      ...              ...           ...          ...  ...   
995   Negra       Sí               Sí     Razonable            8   No   
996  Blanca       No               Sí     Excelente            8   No   
997  Blanca       No               Sí     Muy buena            8   No   
998  Blanca       Sí               No         Buena            6   Sí   
999   Negra       Sí               No     Excelente            7   No   

    Enfermedad_renal Cancer_piel  
0                 No          Sí  
1                 No          No  
2                 No          No  
3                 No          Sí  
4                 No          No  
..               ...         ...  
995               No          No  
996               No          No  
997               No          No  
998               No          No  
999               No          No  

[1000 rows x 19 columns]

In [10]:
datos_pacientes_2 = pd.read_json('../data/pacientes_2.json') # info anidada

In [11]:
datos_pacientes_2

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   
1  Indicadores clave de enfermedades cardíacas  2020   
2  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  {'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol...  
1  {'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio...  
2  {'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol...

# 03 Datos JSON en un DataFrame

A Gustavo se le asignó la tarea de analizar un archivo JSON que contiene información sobre las ventas de una tienda online.

El archivo "ventas.json" contiene información sobre las ventas realizadas por la tienda en los últimos tres meses. Él necesita cargar esta información en un DataFrame de la biblioteca Pandas para poder analizarla.

¿Qué comando se debe utilizar para leer el archivo JSON "ventas.json" con la biblioteca Pandas?

### pd.read_json('ventas.json')

¡Es eso mismo! La función read_json permite cargar un archivo JSON directamente en un DataFrame de la biblioteca Pandas.

## **Normalizando archivos JSON**

### *Para visualizar online: JSON Crack*
![Vista del diagrama generado en JSON Crack](assets/json-crack.png)



In [12]:
df_normalizado = pd.json_normalize(datos_pacientes_2['Pacientes'])

In [13]:
df_normalizado

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

# 05 Para saber más: profundizando en la normalización

La normalización de datos es un proceso importante en la ciencia de datos que tiene como objetivo organizar y estandarizar datos para facilitar el análisis y la comparación entre ellos. Cuando se trata de datos en formato JSON (JavaScript Object Notation - Notación de objetos JavaScript), es común que estén anidados, lo que puede dificultar su análisis y manipulación.

La biblioteca Pandas cuenta con una función llamada json_normalize() que permite la transformación de datos a formato tabular, facilitando la visualización y análisis de las informaciones. A continuación, aprenderemos cómo usar esta función para normalizar diferentes tipos de JSON en DataFrames.

Normalizando un JSON simple

A continuación tenemos una variable llamada datos y dentro de ella hay un objeto JSON con tres llaves y sus respectivos valores:

### datos = {'Análisis': 'Principales indicadores de enfermedad cardíaca', 'Año': 2020, 'Numero_Pacientes':3}

Para normalizar esta variable, podemos pasarla dentro de la función json_normalize y analizar el DataFrame obtenido:

### df = pd.json_normalize(datos)
### df




In [14]:
datos = {'Análisis': 'Principales indicadores de enfermedad cardíaca', 'Año': 2020, 'Numero_Pacientes':3}
df = pd.json_normalize(datos)
df

Análisis   Año  Numero_Pacientes
0  Principales indicadores de enfermedad cardíaca  2020                 3

¡El resultado luce genial! Tenemos 3 columnas que son nuestras llaves y una fila que contiene los valores de cada llave.

### Normalizando un JSON con múltiples niveles

Hay situaciones en las que el archivo JSON puede contener más de un objeto, como es el caso del siguiente ejemplo, en el que tenemos una lista, almacenada en la variable json_lista, que contiene dos objetos JSON:

In [15]:
json_lista = [
    { 'ID': '01', 'Intervalo_edad': '55-59', 'Sexo_biologico': 'femenino'},
    { 'ID': '02', 'Intervalo_edad': '80 ó +', 'Sexo_biologico': 'femenino'}
]
# Para normalizar esta lista podemos aplicar la función json_normalize:

pd.json_normalize(json_lista)

ID Intervalo_edad Sexo_biologico
0  01          55-59       femenino
1  02         80 ó +       femenino

La función json_normalize() es capaz de convertir cada registro de la lista en una línea en forma tabular.

### Normalizando un JSON con una lista anidada

Bueno, notamos que la función json_normalize() funciona muy bien en las situaciones anteriores, pero ¿qué pasa en otras situaciones?

### Datos como un diccionario

Iniciemos observando la normalización cuando los datos son un diccionario. Tenemos un diccionario almacenado en la variable json_obj. Observe que en la llave “Salud” tenemos otro diccionario:

In [16]:
json_obj = {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      }

In [17]:
# Haciendo la normalización:
pd.json_normalize(json_obj)

ID Intervalo_edad Sexo_biologico Salud.Dificultad_caminar  \
0  01          55-59       Femenino                       No   

  Salud.Actividad_fisica  Salud.IMC Salud.Enfermedad_cardiaca  
0                     Sí       16.6                        No

El DataFrame generado tiene una columna para cada información contenida en el diccionario que estaba en “Salud”. Las columnas creadas tienen el prefijo “Salud.”, ya que la información proviene de esa misma llave.

### Datos como una lista de diccionarios.

Ahora tenemos una lista de diccionarios almacenados en la variable json_list:

In [18]:
json_list = [
    {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      },
      {
          'ID': '02',
          'Intervalo_edad': '80 ó +',
          'Sexo_biologico': 'Femenino',
          'Salud': {'Dificultad_caminar': 'No',
                    'Actividad_fisica': 'Sí',
                    'IMC': 20.34,
                    'Enfermedad_cardiaca': 'Sí'}
       }
       ]

In [19]:
# Haciendo la normalización:
pd.json_normalize(json_list)

ID Intervalo_edad Sexo_biologico Salud.Dificultad_caminar  \
0  01          55-59       Femenino                       No   
1  02         80 ó +       Femenino                       No   

  Salud.Actividad_fisica  Salud.IMC Salud.Enfermedad_cardiaca  
0                     Sí      16.60                        No  
1                     Sí      20.34                        Sí

Podemos ver que todos los valores anidados dentro de cada registro de la lista se han convertido en columnas separadas. ¿Qué pasa con los datos que normalizamos en el video anterior? ¿Recuerdas cómo su normalización se hizo de otra manera?

Resumiendo, vamos a copiar los datos del archivo paciente_2.json y vamos a guardarlos en una variable llamada datos_dict.

In [20]:
datos_dict = {
  "Investigación": "Indicadores clave de enfermedades cardíacas",
  "Año": 2020,
  "Pacientes": [
    {
     "ID": "01",
      "Rango_edad": "55-59",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 16.6,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 3,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 5,
      "Problemas_salud": [
        "Diabetes",
        "Asma",
        "Cancer_piel"
      ]
    },
    {
      "ID": "02",
      "Rango_edad": "80 ó +",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 20.34,
      "Fumador": "No",
      "Consumo_alcohol": "No",
      "Salud_física": 0,
      "Salud_mental": 0,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 7,
      "Problemas_salud": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Rango_edad": "65-69",
      "Sexo_biologico": "Masculino",
      "Raza": "Blanca",
      "IMC": 26.58,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 20,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 8,
      "Problemas_salud": [
        "Diabetes",
        "Asma"
      ]
    }
  ]
}

In [21]:
# Si intentamos normalizar estos datos:
pd.json_normalize(datos_dict)

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  [{'ID': '01', 'Rango_edad': '55-59', 'Sexo_bio...

Podemos observar que nuestra lista anidada está colocada en una única columna Pacientes. Entonces, usaremos el siguiente código para normalizar los datos, especificando qué columna está anidada:

In [22]:
pd.json_normalize(datos_dict['Pacientes'])

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

También podemos hacer esto usando el parámetro record_path como ['Pacientes']. Este parámetro se utiliza en la función pd.json_normalize() para especificar la ruta a los registros que deben ser normalizados en un DataFrame separado:

In [23]:
pd.json_normalize(datos_dict, record_path=['Pacientes'])

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

Con ambos códigos el resultado es el mismo.

El resultado parece excelente, pero no incluye las columnas "Investigación" y "Año". Para incluirlas, podemos usar el parámetro meta para especificar otras columnas que queramos en el DataFrame.

In [26]:
pd.json_normalize(
    datos_dict, 
    record_path =['Pacientes'], 
    meta=['Investigación', 'Año']
)

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  \
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]   
1     Muy buena            7                          [AVC]   
2     Muy buena            8               [Diabetes, Asma]   

                                 Investigación   Año  
0  Indicadores clave de enfermedades cardíacas  2020  
1  Indicadores clave de enfermedades cardíacas  2020  
2  Indicadores clave de enfermedades cardíacas  2020

¡De esa manera tenemos todas las columnas presentes en el DataFrame!

* Importante:

 En clase nosotros realizamos la normalización en un archivo con formato JSON. Sin embargo, la función json_normalize() sólo acepta un diccionario o una lista de diccionarios. Por esto, en el video se utilizó la estrategia de usar el código: pd.json_normalize(datos_pacientes_2['Pacientes']). Sin embargo, si intentamos utilizar parámetros de la función json_normalize en un archivo JSON, pueden surgir errores. Para solucionar esto, necesitamos importar el módulo json y leer los archivos según el siguiente código:

In [27]:
#Importando la biblioteca Pandas
import pandas as pd

#Importando el módulo JSON
import json

#Leyendo el archivo json usando el módulo Python JSON
with open('../data/pacientes_2.json','r') as f:
    datos = json.loads(f.read())

#Normalizando los datos con los parámetros record_path y meta
pd.json_normalize(datos, record_path='Pacientes', meta=['Investigación', 'Año'])

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  \
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]   
1     Muy buena            7                          [AVC]   
2     Muy buena            8               [Diabetes, Asma]   

                                 Investigación   Año  
0  Indicadores clave de enfermedades cardíacas  2020  
1  Indicadores clave de enfermedades cardíacas  2020  
2  Indicadores clave de enfermedades cardíacas  2020

Y fue así que aprendimos cómo normalizar archivos JSON simples, con múltiples niveles y anidados.

# **Escribiendo archivos JSON**

In [28]:
df_normalizado.to_json('historico_pacientes_norm.json')

In [30]:
pd.read_json('../data/historico_pacientes_norm.json')

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0   1      55-59          Mujer  Blanca  16.60      Sí              No   
1   2     80 ó +          Mujer  Blanca  20.34      No              No   
2   3      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

## 07 Para saber más: obteniendo archivos JSON de APIs

Para obtener datos en formato JSON podemos utilizar una API (Application Programming Interface). Es una interfaz de programación de aplicaciones que permite la comunicación entre diferentes programas o sistemas.

Hay varios formatos que se pueden utilizar en las API y uno de los más comunes es JSON (JavaScript Object Notation). JSON es un formato ligero para intercambiar información entre sistemas que utiliza la notación basada en objetos de JavaScript.

### Tenemos la siguiente situación-problema:

“Una empresa de alimentos saludables tiene problemas con la popularidad de sus productos. A pesar de ofrecer opciones saludables, muchos clientes se muestran reacios a comprar los productos debido a la falta de información sobre los valores nutricionales de las frutas que se utilizan en la producción de alimentos”.

Ante esta situación podemos acceder a una API llamada Fruitvice para recopilar información detallada sobre los valores nutricionales de las frutas que se utilizan en los productos. Con esta información, la empresa podrá actualizar sus empaques y materiales de marketing para resaltar los valores nutricionales de las frutas y así atraer más clientes que buscan opciones saludables. Además, la empresa puede utilizar la información para desarrollar nuevos productos que satisfagan aún más las necesidades nutricionales de su clientela.

Una forma común de acceder a las API es a través de la biblioteca requests. Para eso, también es necesario importar el módulo json:

In [31]:
import requests
import json

Los datos de API Fruitvice se obtendrán con la función request.get('url'). Dentro de ella pasamos la dirección API seguida de api/fruit/all para obtener los datos de todas las frutas.

In [32]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

Conseguimos recuperar los resultados utilizando la función json.loads(). Para ello es necesario pasar la variable datos_frutas, previamente creada con el atributo text que devuelve el contenido de la respuesta

In [33]:
resultado = json.loads(datos_frutas.text)

Luego podemos obtener una vista previa del DataFrame.

In [36]:
pd.DataFrame(resultado)


name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

                 

¡Ahora sabemos cómo utilizar la biblioteca requests y el módulo JSON para obtener datos de las API!

#  08 Desafío: normalizar el JSON obtenido de la API

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase. El DataFrame que se muestra a continuación se generó después de obtener los datos de la API de Fruitvice:

Este DataFrame tiene 6 columnas: genus (género), name (nombre), id, family (familia), order (orden) e nutritions (nutriciones). Observe que la columna nutritions tiene toda la información nutricional anidada en ella. Por tanto, es necesario normalizar los datos.

El desafío ahora es normalizar este DataFrame.

## Opinión del instructor

Recordando que para obtener los datos de la API debemos utilizar los siguientes códigos:

In [38]:
import requests
import json

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')
resultado = json.loads(datos_frutas.text)

In [39]:
# Ya podrías hacer el DataFrame
import pandas as pd
df = pd.DataFrame(resultado)
df.head()

name  id      family         order      genus  \
0   Persimmon  52   Ebenaceae       Rosales  Diospyros   
1  Strawberry   3    Rosaceae       Rosales   Fragaria   
2      Banana   1    Musaceae  Zingiberales       Musa   
3      Tomato   5  Solanaceae     Solanales    Solanum   
4        Pear   4    Rosaceae       Rosales      Pyrus   

                                          nutritions  
0  {'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c...  
1  {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca...  
2  {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c...  
3  {'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca...  
4  {'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c...

In [40]:
datos_frutas_normalizado = pd.json_normalize(resultado)

In [42]:
datos_frutas_normalizado.head(3)

name  id     family         order      genus  nutritions.calories  \
0   Persimmon  52  Ebenaceae       Rosales  Diospyros                   81   
1  Strawberry   3   Rosaceae       Rosales   Fragaria                   29   
2      Banana   1   Musaceae  Zingiberales       Musa                   96   

   nutritions.fat  nutritions.sugar  nutritions.carbohydrates  \
0             0.0              18.0                      18.0   
1             0.4               5.4                       5.5   
2             0.2              17.2                      22.0   

   nutritions.protein  
0                 0.0  
1                 0.8  
2                 1.0

¡Ahora tenemos todas las informaciones separadas!



# 09 Lo que aprendimos


En esta aula, aprendimos a:

* Comprender qué es el formato JSON;
* Leer un archivo en formato JSON;
* Normalizar datos de un archivo JSON;
* Escribir un archivo en formato JSON;
* Obtener archivos JSON de las API.

# **Aula 4 - Leyendo páginas en HTML e XML**

### **Importando páginas web**

In [46]:
pip install lxml

  Using cached lxml-5.4.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Using cached lxml-5.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (5.1 MB)
Note: you may need to restart the kernel to use updated packages.


In [43]:
import pandas as pd

In [47]:
datos_html = pd.read_html('../data/peliculas_wikipedia.html')

In [48]:
datos_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   

In [49]:
type(datos_html)

list

In [50]:
len(datos_html)

3

In [51]:
top_peliculas = datos_html[1] # segunda posición

In [52]:
top_peliculas

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

#  03 Para saber más: ¿Qué es HTML?

HTML (Hypertext Markup Language - Lenguaje de marcación de hipertexto) es el código que utilizamos para estructurar una página web y su contenido. HTML consta de una serie de elementos que se utilizan para delimitar o agrupar diferentes contenidos para que aparezca o actúe de una determinada manera.

Un documento HTML comienza con la etiqueta < html > y termina con la etiqueta </ html >. También contiene un encabezado (< head >) que describe el título de la página y otras informaciones relevantes; y un cuerpo (< body >) que contiene el contenido de la página. El encabezado y el cuerpo están delimitados por las etiquetas < head > y </ head >, y < body > y </ body >, respectivamente.

Dentro del cuerpo podemos utilizar diversos elementos para crear la estructura del contenido. Observe cada detalle en el siguiente ejemplo:

* tags < h1 > a < h6 >: crear títulos y subtítulos.
* tags < p >: crear párrafos.
* tags < ul > y < li >: crear listas no ordenadas.
* tags < img >: insertar imágenes.
* tags < table >, < tr >, < th > y < td >: crear tablas.

Además, podemos usar atributos en elementos HTML para especificar propiedades adicionales. Por ejemplo: podemos usar el atributo src en la etiqueta < img > para indicar la dirección de la imagen que queremos mostrar, o el atributo href en la etiqueta < a > para indicar la dirección del link que queremos crear.

## 04 Leyendo una tabla específica

Karina está trabajando en un proyecto de análisis de datos y necesita extraer una tabla que está en un archivo HTML. Para ello, decide utilizar la biblioteca Pandas que tiene una función llamada read_html y devuelve una lista de DataFrames de un archivo HTML.

¿Cuál de las siguientes alternativas utiliza correctamente esta función para mostrar la primera tabla contenida en el archivo?

### df = pd.read_html('archivo.html')[0]

Aquí obtenemos el primer elemento de la lista que devuelve la función read_html asignado a la variable df que corresponde a la primera tabla encontrada en el archivo HTML.

## **Escribiendo archivos HTML**

In [53]:
type(top_peliculas)

pandas.core.frame.DataFrame

In [64]:
top_peliculas.to_html('top_peliculas.html', index=False)

In [67]:
pd.read_html('../data/top_peliculas.html')

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   ...   
 95                 The Searchers          1956             John Ford   
 96              Bringing Up Baby          1938          Howard Hawks   
 97                    Unforgiven          1992        Clint Eastwood   
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
 99           Yankee Doodle Dandy          1942        Michael Curtiz   
 
                       Production companies  Rank  
 0                       RKO Radio Pictures     1  
 1                

![imagen del navegador con el archivo html](assets/html.png)

In [59]:
top_peliculas.to_csv('../data/top_peliculas_1998.csv', index=False)

In [60]:
datos = pd.read_csv('../data/top_peliculas_1998.csv')
datos.head()

Film  Release year              Director  \
0        Citizen Kane          1941          Orson Welles   
1          Casablanca          1942        Michael Curtiz   
2       The Godfather          1972  Francis Ford Coppola   
3  Gone with the Wind          1939        Victor Fleming   
4  Lawrence of Arabia          1962            David Lean   

                     Production companies  Rank  
0                      RKO Radio Pictures     1  
1                   Warner Bros. Pictures     2  
2  Paramount Pictures, Alfran Productions     3  
3         Selznick International Pictures     4  
4                        Horizon Pictures     5

# **Leyendo/escribiendo archivos XML**


In [68]:
import pandas as pd

In [69]:
datos_imdb = pd.read_xml('../data/imdb_top_1000.xml')

In [70]:
datos_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

In [71]:
datos_imdb.to_xml('../data/peliculas_imdb.xml')

In [73]:
datos = pd.read_xml('../data/peliculas_imdb.xml')
datos.tail(2)

level_0  index                                        Poster_Link  \
998      998    998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999      999    999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

     Series_Title Released_Year Certificate Runtime                     Genre  \
998      Lifeboat          1944        None  97 min                Drama, War   
999  The 39 Steps          1935        None  86 min  Crime, Mystery, Thriller   

     IMDB_Rating                                           Overview  \
998          7.6  Several survivors of a torpedoed merchant ship...   
999          7.6  A man in London tries to help a counter-espion...   

     Meta_score          Director              Star1              Star2  \
998        78.0  Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999        93.0  Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes Gross  
998   Walter Slezak  William Bendix        26471  None  
999  Lucie Mannheim  Godfrey Tearle        51853  None

## 07 Para saber más: ¿Qué es XML?

XML es un lenguaje de marcación que permite crear y describir datos de forma estructurada y estandarizada. Está compuesto por líneas de comando que utilizan tags (etiquetas) para definir elementos y atributos de los datos.

La estructura básica de un documento XML está formada por:

* Una declaración inicial que indica la versión, el encoding y el tipo del documento.
* Un elemento raíz que contiene todos los demás elementos del documento.
* Elementos secundarios que pueden tener otros elementos o contenido de texto dentro de ellos.
* Atributos que proporcionan información adicional sobre los elementos.
Un ejemplo sencillo de un documento XML es:

In [ ]:
'''
xml
<?xml version="1.0" encoding="UTF-8"?>
<animales>
  <animal nombre="Mel" tipo="perro" color="marron"/>
  <animal nombre="Vick" tipo="gato" color="blanco"/>
</animales>
'''

En este ejemplo, < animales > es el elemento raíz, < animal > es un elemento secundario con tres atributos (nombre, tipo y color) y Mely Vick son el contenido de texto de los elementos.

Podemos encontrar más información sobre la estructura XML en la página: XML para principiantes - Soporte de Microsoft.

##  08 Entendiendo la estructura XML

Gabriel está analizando datos de una tienda online de productos electrónicos. Recibió un archivo XML que contiene informaciones sobre los productos de la tienda, como: nombre, precio y categoría.

In [ ]:
'''
<productos>
  <producto id="1">
    <nombre>Smartphone</nombre>
    <precio>4500.00</precio>
    <categoria>Celulares</categoria>
  </producto>
  <producto id="2">
    <nombre>Notebook</nombre>
    <precio>5000.00</precio>
    <categoria>Computadores</categoria>
  </producto>
  <producto id="3">
    <nombre>Tablet</nombre>
    <precio>2000.00</precio>
    <categoria>Celulares</categoria>
  </producto>
</productos>
'''

El archivo XML se compone de un elemento raíz con nombre < productos > y tres elementos secundarios llamados < < producto >, cada uno con un atributo id.


La alternativa describe correctamente la estructura del archivo XML. Hay un elemento raíz < productos > que contiene todos los demás elementos del documento. Los elementos secundarios < producto > tienen el atributo id.

## Desafío: leer una tabla de una página web

Es el momento de poner a prueba los conocimientos desarrollados durante la clase.

Vanessa es una científica de datos que está haciendo algunos análisis con datos ambientales. Está desarrollando un proyecto para evaluar el impacto ambiental de las actividades humanas en diferentes países del mundo, pero para ello necesita estimaciones de población de esos países. Al buscar en Internet, encontró una tabla de estimaciones de población en un artículo de la página de Wikipedia.

Al igual que Vanessa, tu desafío es obtener un DataFrame de la tabla que contiene la información del número de habitantes de cada país.

### Opinión del instructor

Para leer la página, simplemente pase la dirección a la función read_html. Para que se muestre la primera tabla asignamos el primer elemento de la lista, con [0]:

In [76]:
pd.read_html('https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n')[0]

N.º                   País (o territorio dependiente)  \
0      1                                             India   
1      2                                        China[12]​   
2      3                                    Estados Unidos   
3      4                                         Indonesia   
4      5                                          Pakistán   
..   ...                                               ...   
241  242                           Islas Cocos (Australia)   
242  243  Islas Ultramarinas Menores de los Estados Unidos   
243  244                               Islas Pitcairn (RU)   
244  NaN                                             Mundo   
245   N°                   País (o territorio dependiente)   

    Proyección exponencial de la población al 1/7/2025[7]​  \
0                                        1 417 492 000       
1                                        1 407 934 000       
2                                          342 181 000       
3                                          285 783 000       
4                                          256 204 000       
..                                                 ...       
241                                                600       
242                                                100       
243                                                 30       
244                                      8 085 529 000       
245  Proyección exponencial de la población al 1/7/...       

     Total mun- dial (%) Cambio medio anual (%)[8]​  \
0                   1753                        090   
1                   1741                       -005   
2                    423                        061   
3                    353                        117   
4                    317                        256   
..                   ...                        ...   
241                  000                        174   
242                  000                       -496   
243                  000                       -111   
244                10000                        103   
245  Total mun- dial (%)     Cambio medio anual (%)   

     Cambio absoluto anual promedio  Cambio medio abs. total anual (%)  \
0                        12 692 000                               1521   
1                        -1 390 000                                  -   
2                         2 084 000                                250   
3                         3 337 000                                400   
4                         6 567 000                                787   
..                              ...                                ...   
241                               0                                000   
242                               0                                000   
243                               0                                000   
244                      83 448 000                              10000   
245  Cambio absoluto anual promedio  Cambio medio abs. total anual (%)   

    Años para even- tual du- pli- ca- ción[9]​  \
0                                           78   
1                                            -   
2                                          114   
3                                           60   
4                                           27   
..                                         ...   
241                                         40   
242                                          -   
243                                          -   
244                                         68   
245     Años para even- tual du- pli- ca- ción   

    Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional  \
0                                        1 417 492 000                                                  
1                                        1 408 280 000                                                  
2                                          341 89

¡Y así tendremos la tabla deseada!

##  10 Lo que aprendimos


En esta aula, aprendimos a:

* Inspeccionar una página web;
* Leer datos de una página web;
* Escribir archivos HTML;
* Comprender cómo está estructurado el formato XML;
* Leer datos en formato XML;
* Escribir archivos en formato XML.

## **Aula 5 - Leyendo banco de datos**

### **Creando un banco de datos local**

In [78]:
pip install sqlalchemy

  Using cached sqlalchemy-2.0.41-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
  Using cached greenlet-3.2.2-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Using cached sqlalchemy-2.0.41-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Using cached greenlet-3.2.2-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (580 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [sqlalchemy]2 [sqlalchemy]
Note: you may need to restart the kernel to use updated packages.


In [79]:
import sqlalchemy

In [80]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [81]:
engine = create_engine('sqlite:///:memory:')

##  03 Para saber más: bases de datos y SQLAlchemy

Las bases de datos son sistemas que permiten el almacenamiento, organización y recuperación de información de forma estructurada y eficiente. Se utilizan ampliamente en muchas áreas, desde la gestión empresarial hasta la investigación científica. Una base de datos bien diseñada puede mejorar significativamente la eficiencia y precisión de las operaciones de una organización.

Existen bases de datos relacionales y no relacionales. Las bases de datos relacionales representan y almacenan datos en tablas. Las bases de datos no relacionales, también conocidas como bases de datos NoSQL (Not Only SQL - No Sólo SQL), utilizan una variedad de estructuras de datos, como documentos, gráfos o pares llave-valor.

Python ofrece varios paquetes y bibliotecas para trabajar con bases de datos, incluyendo SQLite, MySQL, PostgreSQL, Oracle, MongoDB, entre otros. Uno de los paquetes más comunes utilizados para trabajar con bases de datos relacionales en Python es el paquete sqlite3 que ofrece soporte a bases de datos SQLite. Esta base de datos es liviana e integrada, no requiere un servidor separado para ejecutarse y está instalada de forma nativa en Google Colab.

Para trabajar con esta base de datos, podemos usar SQLAlchemy, una biblioteca de mapeo objeto-relacional (ORM), que permite interactuar con bases de datos relacionales usando código Python. Proporciona una capa de abstracción que permite a los desarrolladores trabajar con objetos Python en lugar de lidiar directamente con las complejidades del lenguaje SQL (Structured Query Language - Lenguaje de consulta estructurado).

Uno de los principales beneficios de utilizar SQLAchemy es la capacidad de crear código más legible y fácil de mantener. Con SQLAlchemy, las operaciones de la base de datos se realizan utilizando métodos en objetos Python, lo que hace que el código sea más claro y menos propenso a errores.

Además, SQLAlchemy ofrece soporte a consultas complejas en bases de datos, lo que permite a los desarrolladores extraer fácilmente información relevante de grandes conjuntos de datos. Esto es especialmente útil en aplicaciones que necesitan manejar grandes cantidades de datos.

Puede encontrar más detalles sobre la biblioteca SQLAchemy en la siguiente documentación. https://www.sqlalchemy.org/

### **Escribiendo en un banco de datos**

In [82]:
import pandas as pd

In [83]:
archivo = '../data/clientes_banco.csv'

In [84]:
datos = pd.read_csv(archivo)

In [86]:
datos.head()

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0     5008804    32    Nivel superior  Relación-estable               2   
1     5008805    32    Nivel superior  Relación-estable               2   
2     5008806    58  Nivel intermedio            Casado               2   
3     5008808    52  Nivel intermedio           Soltero               1   
4     5008809    52  Nivel intermedio           Soltero               1   

  Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0           Empleado       Otro             12           427500.0   
1           Empleado       Otro             12           427500.0   
2           Empleado  Seguridad              3           112500.0   
3   Business Partner     Ventas              8           270000.0   
4   Business Partner     Ventas              8           270000.0   

   Tiene_carro                  Vivienda  
0            1    Departamento alquilado  
1            1    Departamento alquilado  
2            1  Casa/Departamento propio  
3            0  Casa/Departamento propio  
4            0  Casa/Departamento propio

In [87]:
datos.to_sql('clientes', engine, index=False)

438463

In [88]:
inspector = inspect(engine)

In [89]:
print(inspector.get_table_names())

['clientes']


##  05 Para saber más: cláusulas SQL

SQL (Structured Query Language - Lenguaje de consulta estructurado) es un lenguaje de consulta utilizado en bases de datos relacionales para insertar, actualizar, consultar y administrar datos.

Para hacer todo esto, existen cláusulas SQL, que son componentes fundamentales de las sentencias SQL, permitiendo especificar detalles sobre cómo se va a realizar la consulta u operación de la base de datos. Las cláusulas se utilizan para filtrar, ordenar, agrupar y limitar los resultados de la consulta.

Las sentencias SQL pueden estar compuestas por una o más cláusulas que proporcionan información adicional sobre lo que se supone que debe hacer la consulta. Las cláusulas más comunes son:

* SELECT: especifica qué columnas deben seleccionarse en la consulta.
* FROM: Especifica las tablas de la base de datos que se consultarán.
* WHERE: Filtra los resultados de la consulta según una o más condiciones especificadas.
* ORDER BY: Ordena los resultados de la consulta en orden ascendente o descendente según una o más columnas.
* GROUP BY: agrupa los resultados de la consulta basados en una o más columnas.
* LIMIT: limita el número de filas devueltas por los resultados de la consulta.

Tenemos un ejemplo sencillo de sintaxis SQL que utiliza el comando SELECT para consultar datos de una tabla de empleados en una base de datos:

In [ ]:
'''
SELECT nombre, apellido, salario
FROM empleados
WHERE departamento = 'ventas'
'''


En esta declaración SQL, la cláusula SELECT se utiliza para especificar las columnas que desea consultar de la tabla "empleados", incluyendo "nombre", "apellido" y "salario". La cláusula FROM se utiliza para especificar la tabla que se desea consultar, que en este caso es "empleados".

La cláusula WHERE se utiliza para filtrar los resultados de la consulta según una condición específica. En este ejemplo, la condición es departamento = 'ventas', lo que significa que la consulta solo devolverá empleados que trabajan en el departamento de ventas.

En el próximo vídeo aprenderemos a utilizar algunas de estas cláusulas para realizar las primeras consultas SQL en la tabla que contiene datos de clientes de una institución financiera.

### **Leyendo una consulta SQL**

In [90]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [91]:
empleados = pd.read_sql(sql=text(query), con=engine.connect())

In [92]:
empleados

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [93]:
empleados.to_sql('empleados', con=engine.connect(), index=False)

226059

In [106]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']


In [95]:
pd.read_sql_table('empleados', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [96]:
pd.read_sql_table('empleados', con=engine.connect(), columns=['ID_Cliente', 'Grado_estudio','Rendimiento_anual'])

ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

##  07 read_sql y read_sql_table

Un equipo de análisis de datos está trabajando para extraer información de una tabla en una base de datos SQL. Decidieron utilizar la biblioteca Pandas para acceder a los datos. Para ello utilizaron las funciones

* read_sql y 
* read_sql_table.

¿Cuál es la alternativa correcta sobre estas funciones?

Ambas funciones devuelven un objeto DataFrame.


¡Eso es! Ambas funciones devuelven un DataFrame.

## **Actualizando un banco de datos**

In [97]:
query = 'SELECT * FROM clientes'

In [98]:
pd.read_sql(sql=text(query), con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

In [99]:
#Borrando registros
from sqlalchemy.exc import SQLAlchemyError
query = "DELETE FROM clientes WHERE ID_Cliente=5008804"
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1


In [100]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52  Nivel intermedio           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [ ]:
#Actualizando registros ' Grado_estudio'
query = 'UPDATE clientes SET Grado_estudio="Nivel superior" WHERE ID_Cliente=5008808'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1


In [102]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52    Nivel superior           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [ ]:
#Actualizando registros 'Estado_civil'
query = 'UPDATE clientes SET Estado_civil="Soltero y sin apuros" WHERE ID_Cliente=5008808'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1


In [104]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio          Estado_civil  \
0          5008805    32    Nivel superior      Relación-estable   
1          5008806    58  Nivel intermedio                Casado   
2          5008808    52    Nivel superior  Soltero y sin apuros   
3          5008809    52  Nivel intermedio               Soltero   
4          5008810    52  Nivel intermedio               Soltero   
...            ...   ...               ...                   ...   
438457     6840104    62  Nivel intermedio            Divorciado   
438458     6840222    43  Nivel intermedio               Soltero   
438459     6841878    22    Nivel superior               Soltero   
438460     6842765    59  Nivel intermedio                Casado   
438461     6842885    51  Nivel intermedio                Casado   

        Tamaño_familia Categoria_de_renta           Ocupacion  Años_empleado  \
0                    2           Empleado                Otro             12   
1                    2           Empleado           Seguridad              3   
2                    1   Business Partner              Ventas              8   
3                    1   Business Partner              Ventas              8   
4                    1   Business Partner              Ventas              8   
...                ...                ...                 ...            ...   
438457               1        Pensionista                Otro              0   
438458               1           Empleado  Construcción Civil              8   
438459               1   Business Partner              Ventas              1   
438460               2        Pensionista                Otro              0   
438461               2           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [105]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']


##  09 Desafío: manipulando una base de datos

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase.

Usted es responsable de crear una base de datos local de clientes para una institución financiera. Disponemos del archivo CSV con los datos de los clientes.

### Tu misión es:

* 1-Crear la base de datos local con la biblioteca SQLAlchemy.
* 2-Escribir los datos del archivo CSV en esta base de datos local.
* 3-Realizar tres actualizaciones en la base de datos:
* 4-Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
* 5-Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
* 6-Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
* 7-ID_cliente: 6850985
* 8-Edad: 33
* 9-Grado_estudio: Doctorado
* 10-Estado_civil: Soltero
* 11-Tamaño_familia: 1
* 12-Categoria_de_renta: Empleado
* 13-Ocupacion: TI
* 14-Años_empleado: 2
* 15-Rendimiento_anual: 290000
* 16-Tiene_carro: 0
* 17-Vivienda: Casa/Departamento propio

### Consejo importante:

Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

## Opinión del instructor

Para crear la base de datos local es necesario ejecutar los siguientes comandos. Este código consiste en importar la biblioteca sqlalchemy y crear un objeto engine que representa una conexión a una base de datos SQLite en memoria. El método create_engine se utiliza para crear el objeto engine y especificar la base de datos que se utilizará. En este caso, la base de datos es una base de datos SQLite en memoria, que se crea usando sqlite:///:memory::

In [107]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

A continuación, podemos leer los datos con la función read_csv y escribirlos en el formato de la base de datos con la función to_sql:

In [109]:
import pandas as pd
archivo = '../data/clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

438463

Después de crear la tabla, podemos obtener un DataFrame con la función read_sql_table:

In [110]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

¡Ahora vamos a comenzar las actualizaciones de la base de datos!

Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000:

El siguiente código actualiza el rendimiento anual del ID de cliente 6840104 en la tabla clientes. La variable query contiene una declaración SQL que actualiza ese registro. Luego, la declaración engine.connect() se usa para crear una conexión a la base de datos SQLite. Finalmente, la declaración .execute(text(query)) se utiliza para ejecutar la declaración SQL contenida en la variable query y actualizar el registro en la tabla clientes.

In [111]:
from sqlalchemy.exc import SQLAlchemyError
query = 'UPDATE clientes SET Rendimiento_anual=300000.0 WHERE ID_Cliente=6840104'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1


Después de ejecutar este código, puede verificar si la actualización realmente ocurrió leyendo la tabla "clientes"

In [112]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           300000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene una cuenta en la institución financiera:

In [113]:
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1


In [114]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           300000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

Cree un nuevo registro de cliente siguiendo las especificaciones dadas anteriormente:

Al trabajar con bases de datos, es común necesitar insertar nuevos registros en nuestras tablas. Para ello podemos utilizar la cláusula INSERT INTO que nos permite añadir nuevos datos de forma práctica y rápida.

Para utilizar esta cláusula, primero debe especificar el nombre de la tabla en la que se insertará el registro. A continuación, debemos pasar entre paréntesis los nombres de las columnas donde se agregarán los nuevos valores. Es importante recordar que el orden de los nombres debe ser el mismo orden en el que se pasarán los valores.

Después de especificar las columnas, usamos la cláusula VALUES para agregar los nuevos valores. Nuevamente debemos pasar entre paréntesis los valores a insertar en el mismo orden en que se especificaron las columnas. Es importante asegurarse de que los valores estén en el formato correcto para cada tipo de datos.

Como la `query` es larga, puedes usar `' \` para indicar que el código continúa en la siguiente línea.

In [115]:
from sqlalchemy.exc import SQLAlchemyError
query = 'INSERT INTO clientes (ID_Cliente, Edad, Grado_estudio, Estado_civil, ' \
        'Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, ' \
        'Rendimiento_anual, Tiene_carro, Vivienda) ' \
        'VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", ' \
        '2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros insertados: ",r_set.rowcount)

#Registros insertados:  1


Para verificar que se realizaron los cambios, puede leer la tabla con el siguiente código:

In [116]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   
438462     6850985    33         Doctorado           Soltero               1   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   
438462           Empleado                  TI              2   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  
438462           290000.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

¡Misión completada con éxito!

#  11 Lo que aprendimos


En esta aula, aprendimos a:

* Crear una base de datos local;
* Escribir en una base de datos;
* Realizar lectura en una consulta SQL;
* Actualizar una base de datos.